// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/project-card-actions/Current.tsx": () => import("../components/mockups/project-card-actions/Current.tsx"),
  "./components/mockups/project-card-actions/Refined.tsx": () => import("../components/mockups/project-card-actions/Refined.tsx"),
  "./components/mockups/social-content/WeekOneBoard.tsx": () => import("../components/mockups/social-content/WeekOneBoard.tsx")
};
